Assignment2WebApp/Controllers/SubjectController.cs
using ApplicationDatabase;
using Entities;
using RepositoryServices.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Assignment2WebApp.Controllers
{
    public class SubjectController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        UnitOfWork unit;

        public SubjectController()
        {
            unit = new UnitOfWork(db);
        }

        // GET: Subject
        public ActionResult Index()
        {
            var subjects = unit.Subjects.GetAll();
            if (subjects != null)
            {
                return View(subjects);
            }

            return new HttpStatusCodeResult(HttpStatusCode.NotFound);

        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var subject = unit
                    .Subjects
                    .GetById(id);

                if (subject != null)
                {
                    return View(subject);
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Subject subject)
        {
            if (ModelState.IsValid)
            {
                unit.Subjects.Update(subject);
                unit.Subjects.Save();

                ShowAlert($"Subject with id {subject.SubjectId} has been successfully updated");

                return RedirectToAction("Index");
            }

            return View(subject);
        }

        [HttpGet]
        public ActionResult Create()
        {
            GetTrainersToViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Subject subject)
        {
            if (ModelState.IsValid)
            {
                unit.Subjects.Insert(subject);
                unit.Subjects.Save();
                ShowAlert($"Subject with id {subject.SubjectId} has been successfully created");
                return RedirectToAction("Index");
            }

            GetTrainersToViewBag();
            return View(subject);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                var subject = unit.Subjects.GetById(id);
                var trainers = unit.Trainers.GetBySubjectId(id);  //Get all trainers where subjecId is equal to given id

                if (trainers != null)  //Set subjectId FK to null so as to delete the subject afterwards
                {
                    foreach (var trainer in trainers)
                    {
                        unit.Trainers.SetSubjectIdToNull(trainer);
                        unit.Trainers.Save();
                    }
                }

                if (subject != null)
                {
                    unit.Subjects.Delete(subject);
                    unit.Subjects.Save();
                    ShowAlert($"Subject with id {id} has been successfully deleted");
                    return RedirectToAction("Index");
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
        }

        public void GetTrainersToViewBag()
        {
            var trainers = unit.Trainers.GetAll();
            ViewBag.trainers = trainers;
        }

        public void ShowAlert(string message)
        {
            TempData["subjectMessage"] = message;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2WebApp/Controllers/TrainerController.cs
using ApplicationDatabase;
using Entities;
using RepositoryServices.Persistence;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Assignment2WebApp.Controllers
{
    public class TrainerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private UnitOfWork unit;

        public TrainerController()
        {
            unit = new UnitOfWork(db);
        }

        // GET: Trainer
        public ActionResult Index(int? psize, int? pnumber)
        {
            var trainers = unit.Trainers.GetAllWithSubject();
            if (trainers != null)
            {

                return View(trainers);
            }

            return new HttpStatusCodeResult(HttpStatusCode.NotFound);

        }

        public ActionResult Details(int? id)
        {
            var trainers = unit.Trainers.GetByIdWithSubject(id);
            return View(trainers);
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {
            if (id != null)
            {
                var trainer = unit
                    .Trainers
                    .GetByIdWithSubject(id);

                if (trainer != null)
                {
                    GetSubjectsToViewBag();
                    return View(trainer);
                }
            }

            return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trainer trainer, List<int> subjects)
        {
            if (ModelState.IsValid)
            {
                unit.Trainers.Update(trainer);
                unit.Trainers.Save();
                return RedirectToAction("Index");
            }

            GetSubjectsToViewBag();
            return View(trainer);
        }


        [HttpGet]
        public ActionResult Create()
        {
            GetSubjectsToViewBag();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trainer trainer, List<int> subjectsIds)
        {
            if (ModelState.IsValid)
            {
                unit.Trainers.Insert(trainer);
                unit.Trainers.Save();
                ShowAlert($"Trainer with id {trainer.TrainerId} has been successfuly created");
                return RedirectToAction("Index");
            }

            GetSubjectsToViewBag();
            return View(trainer);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            var trainer = db.Trainers.Find(id);

            if (trainer == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            unit.Trainers.Delete(trainer);
            unit.Trainers.Save();
            ShowAlert($"Trainer with id {trainer.TrainerId} has been successfully been deleted");
            return RedirectToAction("Index");
        }

        public void GetSubjectsToViewBag()
        {
            var subjects = unit.Subjects.GetAll();
            ViewBag.subjects = subjects;
        }

        public void ShowAlert(string message)
        {
            TempData["trainerMessage"] = message;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                unit.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Assignment2WebApp/Views/Shared/_Footer.cshtml
<footer>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer>

Assignment2WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <!--navBar-->
    @Html.Partial("~/Views/Shared/_NavBar.cshtml")
    <!--end navBar-->
    
    <div class="container body-content">
        @RenderBody()
        <hr />
        <!--footer-->
        @Html.Partial("~/Views/Shared/_Footer.cshtml")
        <!--end footer-->
    </div>
    

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/boostrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Assignment2WebApp/Views/Shared/_NavBar.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Trainers", "Index", "Trainer")</li>
                <li>@Html.ActionLink("Subjects", "Index", "Subject")</li>
            </ul>
        </div>
    </div>
</div>

Assignment2WebApp/Views/Subject/Create.cshtml
@model Entities.Subject
@using Entities


<div>
    <h1>
        <u>
            <strong>Create Subject</strong>
        </u>
    </h1>
</div>

<div>
    <form method="post">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="titleId">Title</label>
            <input id="titleId" class="form-control" type="text" name="title" value="@(Model?.Title)" placeholder="Give title" />
            @Html.ValidationMessageFor(s => s.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input class="btn btn-success" type="submit" value="Create" />
            <input class="btn btn-danger" type="reset" value="Clear" />
        </div>
    </form>
</div>

<div>
    <a class="btn btn-primary" style="width:100px" href="/Subject/index">Back</a>
</div>

Assignment2WebApp/Views/Subject/Edit.cshtml
@model Entities.Subject


<div>
    <h1>
        <u>
            <strong>Edit Subject</strong>
        </u>
    </h1>
</div>

<div>
    <form method="post">
        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="titleId">Title</label>
            <input id="titleId" class="form-control" type="text" name="title" value="@(Model?.Title)" placeholder="Give title" />
            @Html.ValidationMessageFor(s => s.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <input type="hidden" name="subjectId" value="@Model.SubjectId" />
            <input class="btn btn-success" type="submit" value="Save" />
        </div>
    </form>
</div>

<div>
    <a class="btn btn-primary" style="width:100px" href="/Subject/index">Back</a>
</div>

Assignment2WebApp/Views/Subject/Index.cshtml
@model IEnumerable<Entities.Subject>


<div>
    <h1>
        <u>Subjects</u>
    </h1>
</div>

@if (TempData["subjectMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["subjectMessage"]
    </div>
}

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var subject in Model)
            {
                <tr>
                    <td>@subject.SubjectId</td>
                    <td>@subject.Title</td>
                    <td>
                        <div class="row align-items-end">
                            
                            <div class="form-group col-5 col-md-2 ">

                                <div class="form-group">
                                    <a class="btn btn-success" href="/Subject/Edit?id=@subject.SubjectId">Edit</a>
                                </div>

                            </div>

                            <div class="form-group col-5 col-md-2">

                                <form method="post" action="/Subject/Delete">
                                    <input type="hidden" name="id" value="@subject.SubjectId" />
                                    <input class="btn btn-danger" type="submit" value="Delete" />
                                </form>

                            </div>

                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

<div>
    <a class="btn btn-primary" href="/Subject/Create">Create Subject</a>
</div>

Assignment2WebApp/Views/Trainer/Create.cshtml
@model Entities.Trainer
@using Entities

<div>
    <h1>
        <u>
            <strong>Create Trainer</strong>
        </u>
    </h1>
</div>
<br />

<div>
    <form method="post">

        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="firstNameID">First Name</label>
            <input id="firstNameID" class="form-control" type="text" name="firstName" value="@(Model?.FirstName)" placeholder="Give first name"/>
            @Html.ValidationMessageFor(m => m.FirstName, "", new { @class="text-danger"})
        </div>

        <div class="form-group">
            <label for="lastNameId">Last Name</label>
            <input id="lastNameId" class="form-control" type="text" name="lastName" value="@(Model?.LastName)" placeholder="Give last name"/>
            @Html.ValidationMessageFor(m => m.LastName, "", new { @class="text-danger"})
        </div>

        <div class="form-group">
            <label for="dateHiredId">Date Hired</label>
            <input id="dateHiredId" class="form-control" type="date" name="dateHired" value="@(Model?.DateHired)" placeholder="Select hire date"/>
            @Html.ValidationMessageFor(m => m.DateHired, "", new { @class="text-danger"})
        </div>

        <div class="form-group">
            <label for="photoUrlId">Photo URL</label>
            <input id="photoUrlId" class="form-control" type="url" name="photoUrl" value="@(Model?.PhotoUrl)" placeholder="Give photo URL"/>
            @Html.ValidationMessageFor(m => m.PhotoUrl, "", new { @class="text-danger"})
        </div>

        <div class="form-group">
            <label for="subject">Subjets</label>
            <select name="subjectId" id="subject" class="form-control">
                <option selected disabled>No subject</option>
                @foreach (var subject in ViewBag.subjects as List<Subject>)
                {
                    <option value="@subject.SubjectId">@subject.Title</option>
                }
            </select>
        </div>

        <input class="btn btn-success" type="submit"  value="Create" />
        <input class="btn btn-danger" type="reset"  value="Clear" />
    </form>
</div>
<br />

<div>
    <a style="width:100px" class="btn btn-primary" href="/Trainer/Index">Back</a>
</div>

Assignment2WebApp/Views/Trainer/Details.cshtml
@model Entities.Trainer

<div>
    <h1>
        <u>
            <strong>Trainer Details</strong>
        </u>
    </h1>
</div>
<br />

<div>
    <span>
        <img style="width:200px; height:300px" src="@Model.PhotoUrl" alt="Trainer Photo" />
    </span>
</div>
<br />

<div>
    <strong>First Name:</strong>
    <span>@Model.FirstName</span>
</div>

<div>
    <strong>Last Name:</strong>
    <span>@Model.LastName</span>
</div>

<div>
    <strong>Date Hired:</strong>
    <span>@Model.DateHired</span>
</div>

<div>
    <strong>Subject:</strong>
    <span>@(Model.Subject != null ? Model.Subject.Title : "No Subject assigned yet")</span>
</div>
<br />

<div>
    <a class="btn btn-primary" style="width:100px" href="/Trainer/Index">Back</a>
</div>

Assignment2WebApp/Views/Trainer/Edit.cshtml
@model Entities.Trainer
@using Entities

<div>
    <h1>
        <u>
            <strong>Edit Trainer</strong>
        </u>
    </h1>
</div>
<br />

<div>
    <form method="post">

        @Html.AntiForgeryToken()

        <div class="form-group">
            <label for="firstNameID">First Name</label>
            <input id="firstNameID" class="form-control" type="text" name="firstName" value="@(Model?.FirstName)" placeholder="Give first name" />
            @Html.ValidationMessageFor(m => m.FirstName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="lastNameId">Last Name</label>
            <input id="lastNameId" class="form-control" type="text" name="lastName" value="@(Model?.LastName)" placeholder="Give last name" />
            @Html.ValidationMessageFor(m => m.LastName, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="dateHiredId">Date Hired</label>
            <input id="dateHiredId" class="form-control" type="date" name="dateHired" value="@(Model?.DateHired)" placeholder="Select hire date" />
            @Html.ValidationMessageFor(m => m.DateHired, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="photoUrlId">Photo URL</label>
            <input id="photoUrlId" class="form-control" type="url" name="photoUrl" value="@(Model?.PhotoUrl)" placeholder="Give photo URL" />
            @Html.ValidationMessageFor(m => m.PhotoUrl, "", new { @class = "text-danger" })
        </div>

        <div class="form-group">
            <label for="subject">Subjets</label>
            <select name="subjectId" id="subject" class="form-control">
                <option selected disabled>No subject</option>
                @foreach (var subject in ViewBag.subjects as List<Subject>)
                {
                    <option value="@subject.SubjectId" @(Model.SubjectId == subject.SubjectId ? "selected" : "")>@subject.Title</option>
                }
            </select>
        </div>

        <div class="form-group">
            <input type="hidden" name="trainerId" value="@Model.TrainerId" />
            <input class="btn btn-success" type="submit" value="Save" />
        </div>
    </form>
</div>
<br />

<div>
    <a style="width:100px" class="btn btn-primary" href="/Trainer/Index">Back</a>
</div>

Assignment2WebApp/Views/Trainer/Index.cshtml
@model IEnumerable<Entities.Trainer>

<style>
    td img {
        width: 100px;
        height: 170px;
    }

    tr:hover {
        background-color: lightgray;
    }
</style>

<div>
    <h1>
        <u>Trainers</u>
    </h1>
</div>


@if (TempData["trainerMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Success!</strong> @TempData["trainerMessage"]
    </div>
}

<div>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Photo</th>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Date Hired</th>
                <th>Subject</th>
                <th>Actions</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var trainer in Model)
            {
                <tr>

                    <td>@trainer.TrainerId</td>
                    <td>
                        <img src="@trainer.PhotoUrl" alt="Trainer Photo" />
                    </td>
                    <td>@trainer.FirstName</td>
                    <td>@trainer.LastName</td>
                    <td>@trainer.DateHired</td>
                    <td>@(trainer.Subject != null ? trainer.Subject?.Title : "No Subject assigned yet")</td>
                    <td>
                        <a class="btn btn-primary" href="/Trainer/Details?id=@trainer.TrainerId">Details</a>
                        <a class="btn btn-success" href="/Trainer/Edit?id=@trainer.TrainerId">Edit</a>
                        <form method="post" action="/Trainer/Delete">
                            <input type="hidden" name="id" value="@(trainer?.TrainerId)" />
                            <input class="btn btn-danger" type="submit" name="name" value="Delete" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>

<div>
    <a class="btn btn-primary" href="/Trainer/Create">Create Trainer</a>
</div>